# Generated by Django 2.2.4 on 2019-08-20 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20190820_0124'),
        ('registros_horas_extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasextras',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
            preserve_default=False,
        ),
    ]
